export const FIELD_LABELS: Record<string, string> = {
  W1: "Width",
  D1: "Diameter 1",
  D2: "Diameter 2",
  D3: "Diameter 3",
  D4: "Diameter 4",
  D5: "Diameter 5",
  W2: "Width 2",
  W3: "Width 3",
  L: "Length",
  A: "Angle (deg)",
  R: "Radius",
  R1: "Radius 1",
  R2: "Radius 2",
  O: "Offset",
  O1: "Offset 1",
  O2: "Offset 2",
  S1: "Offset S1",
  S2: "Offset S2",
  S3: "Offset S3",
  S4: "Offset S4",
  TD: "Throat Depth",
  TD1: "Throat Depth 1",
  TD2: "Throat Depth 2",
  T: "Thickness",
  TJ: "TJ",
  TV: "Turning Vanes",
  M: "M",
  GA: "Gauge",
};

export const inputClass =
  "w-full rounded-xl border border-black/10 bg-white px-4 py-3 text-sm text-black shadow-soft focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-red focus-visible:ring-offset-2";
